// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/6/10 10:46:50
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/plugins/**/*.{js,ts,mjs}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/composables/**/*.{js,ts,mjs}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/utils/**/*.{js,ts,mjs}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/app.config.{js,ts,mjs}","/Users/yuyasato/Documents/devs/OsakaUniv_ThemeMatch/OsakaUniv_ThemeMatch_Public/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;