name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .output
            .nuxt
            node_modules
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-

      - name: Install dependencies
        run: npm ci

      - name: Static HTML export with Nuxt
        run: |
          echo "Building with NODE_ENV=production"
          npm run generate
        env:
          NODE_ENV: production
          NODE_OPTIONS: --max-old-space-size=4096

      - name: List build output
        run: |
          echo "Build output contents:"
          ls -la .output/
          if [ -d ".output/public" ]; then
            echo "Public directory contents:"
            ls -la .output/public/
          else
            echo "ERROR: .output/public directory not found"
            exit 1
          fi

      - name: Prepare for upload
        run: |
          # Create a clean directory for upload
          mkdir -p upload
          # Copy all files to avoid hard link issues
          cp -r .output/public/* upload/ 2>/dev/null || cp -r .output/public/. upload/
          # Add .nojekyll to disable Jekyll processing
          touch upload/.nojekyll
          echo "Upload directory prepared successfully"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./upload

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4