name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # Setup Pagesをコメントアウト（自前でbaseURL設定済み）
      # - name: Setup Pages
      #   uses: actions/configure-pages@v4
      #   with:
      #     static_site_generator: nuxt

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .output
            .nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('.output') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-

      - name: Install dependencies
        run: npm ci

      - name: Static HTML export with Nuxt
        run: npm run generate

      - name: Disable Jekyll
        run: touch .output/public/.nojekyll

      - name: De-link hard links for GitHub Pages
        run: |
          # Copy all files, resolving hard links to actual file copies
          rsync -aL .output/public/ public-no-links/
          # Verify no hard links remain
          echo "Checking for remaining hard links..."
          find public-no-links -type f -links +1 | wc -l
          echo "Hard link removal completed"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public-no-links

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4